### ISSUE TITLE
An inquiry regarding MENP

### ISSUE THREAD

**Issue by am987654321** [Hinamoooon/MENP#2]
Dear Dr. Tatsuki,

Thank you for this great work. It should be an essential tool for researchers in the field of Mie resonators. I  am trying to use MENP to carry out the multipole expansion of a design and I have some questions, please.
(1) The design is a periodic array of nanoresonators, do I need to change anything in the files regarding the periodicity? 
(2) The design is a hybrid resonator, consisting of metallic aluminum (Al) disk with a silicon (Si) disk on top of the Al disk. I want to calculate the contribution of the electric dipole of Al and the modal contributions of Si at the same time. Can I add monitors around Al and other monitors around Si to get the total modal expansion? 
(3) I noticed that you are using 2 sets of field monitors at different distances from the resonator. I am thinking of using field monitors at the edge of each resonator. What do you think, please?

**Comment by Hinamoooon** [comment]
Dear @am987654321 ,
Thank you for the questions, and sorry for the late response.

> (1) The design is a periodic array of nanoresonators, do I need to change anything in the files regarding the periodicity?

The MATLAB code works fine as well for periodic arrays. In Lumerical, electric field and refractive index monitors should include a unit of the nanostructure.

> (2) The design is a hybrid resonator, consisting of metallic aluminum (Al) disk with a silicon (Si) disk on top of the Al disk. I want to calculate the contribution of the electric dipole of Al and the modal contributions of Si at the same time. Can I add monitors around Al and other monitors around Si to get the total modal expansion?

I think it is difficult to separate each contribution of Al and Si in the hybrid structure because they "hybridize". In the hybrid structure, a monitor should be put as it includes the whole hybrid structure. To see each contribution, I recommend running separate simulations for Al (w/o Si) and Si (w/o Al).

> (3) I noticed that you are using 2 sets of field monitors at different distances from the resonator. I am thinking of using field monitors at the edge of each resonator. What do you think, please?

Could you clarify the fsp file you are talking about?
